// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKPn2E-J5mf-ziL3XttpA94nF9hJCIdjg',
    appId: '1:857738793657:web:e9ab5f776a6a3128ebc168',
    messagingSenderId: '857738793657',
    projectId: 'shopee-54230',
    authDomain: 'shopee-54230.firebaseapp.com',
    storageBucket: 'shopee-54230.appspot.com',
    measurementId: 'G-JNZ3KJ8CPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp08W9K_BSLJhiIYkB7tr24Trepd-3NvA',
    appId: '1:857738793657:android:2a402ad478c244bcebc168',
    messagingSenderId: '857738793657',
    projectId: 'shopee-54230',
    storageBucket: 'shopee-54230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09NCqq-SOqrP9Lor42ryIPWTDJVZ6uDk',
    appId: '1:857738793657:ios:e399ac08fd143ca3ebc168',
    messagingSenderId: '857738793657',
    projectId: 'shopee-54230',
    storageBucket: 'shopee-54230.appspot.com',
    iosBundleId: 'com.example.shopeeSellerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09NCqq-SOqrP9Lor42ryIPWTDJVZ6uDk',
    appId: '1:857738793657:ios:4814ed6a80035505ebc168',
    messagingSenderId: '857738793657',
    projectId: 'shopee-54230',
    storageBucket: 'shopee-54230.appspot.com',
    iosBundleId: 'com.example.shopeeSellerApp.RunnerTests',
  );
}
